### ISSUE TITLE
Node.js v4.1.1で`let`は使えないのか調査する

### ISSUE THREAD

**Issue by pollseed** [pollseed/hogechan-io-socket#8]

**Comment by pollseed** [comment]
古いが、es6のnode用の例がのってる。https://github.com/JustinDrake/node-es6-examples/blob/master/README.md

**Comment by pollseed** [comment]
使えない

**Comment by pollseed** [comment]
#### ログ

一応そのログ

``` .js
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```
